name: Build
on:
  push:
  workflow_dispatch:
  schedule:
    # Every Monday at 12am
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.ref }}-latest
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Compile Counter using mono
        shell: bash
        id: compile
        run: |
          msbuild Counters.sln /p:Configuration=Release
          msbuild Starter/Starter.csproj /p:Configuration=Release
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'Bin/Release'
          DEST_NAME: 'Counter'
          NOTIFY_MESSAGE: 'Successfully compiled Counter!'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
     
      - uses: ./.github/actions/notify_failure
        if: failure()
        with:
          NOTIFY_MESSAGE: 'Failed to compile Counter! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'